commands:
  N98\Magento\Command\Installer\InstallCommand:
    magento-packages:
      - name: magento-ce-1.9.2.4
        version: 1.9.2.4
        dist:
          url: /tmp/magento-ce-1.9.2.4.zip
          type: zip
          shasum: 219fe2b88068cf73953b90ce01186cb1f19affea

      - name: magento-ce-1.9.2.3
        version: 1.9.2.3
        dist:
          url: /tmp/magento-ce-1.9.2.3.zip
          type: zip
          shasum: c211c1d31468dfbc45decd7d00266281fdc97b20

      - name: magento-ce-1.9.2.2
        version: 1.9.2.2
        dist:
          url: /tmp/magento-ce-1.9.2.2.zip
          type: zip
          shasum: 6b6de6bee57a2992affa1fad01444cb6c05e0788

      - name: magento-ce-1.9.2.1
        version: 1.9.2.1
        dist:
          url: /tmp/magento-ce-1.9.2.1.zip
          type: zip
          shasum: b158de5c3bc587931d99af1bd11f3235e75d1191

      - name: magento-ce-1.9.2.0
        version: 1.9.2.0
        dist:
          url: /tmp/magento-ce-1.9.2.0.zip
          type: zip
          shasum: f5cd7053c41f19e9007ce6817ad12344e6fc0263

      - name: magento-ce-1.9.1.1
        version: 1.9.1.1
        dist:
          url: /tmp/magento-ce-1.9.1.1.zip
          type: zip
          shasum: c9074bf9646b28c035d369db7189aec9733ea978

      - name: magento-ce-1.9.1.0
        version: 1.9.1.0
        dist:
          url: /tmp/magento-ce-1.9.1.0.zip
          type: zip
          shasum: ef2da3723033614d4f10c3a12e8392d1730ade30

      - name: magento-ce-1.9.0.1
        version: 1.9.0.1
        dist:
          url: /tmp/magento-ce-1.9.0.1.zip
          type: zip
          shasum: ff84a32100598cff43d765e3d6cb0bc1a5a414b3

      - name: magento-ce-1.9.0.0
        version: 1.9.0.0
        dist:
          url: /tmp/magento-ce-1.9.0.0.zip
          type: zip
          shasum: 089664d5c690324a53f06f0311d1126cf0ba3044

      - name: magento-ce-1.8.1.0
        version: 1.8.1.0
        dist:
          url: /tmp/magento-ce-1.8.1.0.zip
          type: zip
          shasum: 9b47925c8e68a4eea0963e32af884944e3b90ee0

      - name: magento-ce-1.8.0.0
        version: 1.8.0.0
        dist:
          url: /tmp/magento-ce-1.8.0.0.zip
          type: zip
          shasum: 51a140dc651e1d2e3693571f86963a01c168f740

      - name: magento-ce-1.7.0.2
        version: 1.7.0.2
        dist:
          url: /tmp/magento-ce-1.7.0.2.zip
          type: zip
          shasum: 0183fac38b6c5a6ff13b9363304eb70d9298b759

      - name: magento-ce-1.6.2.0
        version: 1.6.2.0
        dist:
          url: /tmp/magento-ce-1.6.2.0.zip
          type: zip
          shasum: 136a5ce5d49cc7d4fd6a43452aafcfbac97722be